//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_desktopp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Employee_ID { get; set; }
        public string email { get; set; }
        public string name_ { get; set; }
        public string password { get; set; }
        public string employee_role { get; set; }
        public string department { get; set; }
        public Nullable<System.DateTime> join_date { get; set; }
        public string system_role { get; set; }
    }
}
