//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_desktopp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday
    {
        public int Holiday_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public Nullable<System.DateTime> holiday_start { get; set; }
        public Nullable<System.DateTime> holiday_end { get; set; }
        public Nullable<bool> holiday_approved { get; set; }
        public Nullable<bool> constraints_broken { get; set; }
    }
}
