//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_Desktop.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempurideya.org/", ConfigurationName="ServiceReference1.TheWebServiceSoap")]
    public interface TheWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempurideya.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempurideya.org/login_employee", ReplyAction="*")]
        Employee_Desktop.ServiceReference1.login_employeeResponse login_employee(Employee_Desktop.ServiceReference1.login_employeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempurideya.org/login_employee", ReplyAction="*")]
        System.Threading.Tasks.Task<Employee_Desktop.ServiceReference1.login_employeeResponse> login_employeeAsync(Employee_Desktop.ServiceReference1.login_employeeRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempurideya.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempurideya.org/submit_holiday_request", ReplyAction="*")]
        Employee_Desktop.ServiceReference1.submit_holiday_requestResponse submit_holiday_request(Employee_Desktop.ServiceReference1.submit_holiday_requestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempurideya.org/submit_holiday_request", ReplyAction="*")]
        System.Threading.Tasks.Task<Employee_Desktop.ServiceReference1.submit_holiday_requestResponse> submit_holiday_requestAsync(Employee_Desktop.ServiceReference1.submit_holiday_requestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class login_employeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login_employee", Namespace="http://tempurideya.org/", Order=0)]
        public Employee_Desktop.ServiceReference1.login_employeeRequestBody Body;
        
        public login_employeeRequest() {
        }
        
        public login_employeeRequest(Employee_Desktop.ServiceReference1.login_employeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempurideya.org/")]
    public partial class login_employeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public login_employeeRequestBody() {
        }
        
        public login_employeeRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class login_employeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login_employeeResponse", Namespace="http://tempurideya.org/", Order=0)]
        public Employee_Desktop.ServiceReference1.login_employeeResponseBody Body;
        
        public login_employeeResponse() {
        }
        
        public login_employeeResponse(Employee_Desktop.ServiceReference1.login_employeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempurideya.org/")]
    public partial class login_employeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool login_employeeResult;
        
        public login_employeeResponseBody() {
        }
        
        public login_employeeResponseBody(bool login_employeeResult) {
            this.login_employeeResult = login_employeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class submit_holiday_requestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="submit_holiday_request", Namespace="http://tempurideya.org/", Order=0)]
        public Employee_Desktop.ServiceReference1.submit_holiday_requestRequestBody Body;
        
        public submit_holiday_requestRequest() {
        }
        
        public submit_holiday_requestRequest(Employee_Desktop.ServiceReference1.submit_holiday_requestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempurideya.org/")]
    public partial class submit_holiday_requestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime holiday_start;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime holiday_end;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string holiday_status;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool days_exceeded;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool head_depHead_absent;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool seniorStaff_absent;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool Department_absent;
        
        public submit_holiday_requestRequestBody() {
        }
        
        public submit_holiday_requestRequestBody(string email, System.DateTime holiday_start, System.DateTime holiday_end, string holiday_status, bool days_exceeded, bool head_depHead_absent, bool seniorStaff_absent, bool Department_absent) {
            this.email = email;
            this.holiday_start = holiday_start;
            this.holiday_end = holiday_end;
            this.holiday_status = holiday_status;
            this.days_exceeded = days_exceeded;
            this.head_depHead_absent = head_depHead_absent;
            this.seniorStaff_absent = seniorStaff_absent;
            this.Department_absent = Department_absent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class submit_holiday_requestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="submit_holiday_requestResponse", Namespace="http://tempurideya.org/", Order=0)]
        public Employee_Desktop.ServiceReference1.submit_holiday_requestResponseBody Body;
        
        public submit_holiday_requestResponse() {
        }
        
        public submit_holiday_requestResponse(Employee_Desktop.ServiceReference1.submit_holiday_requestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class submit_holiday_requestResponseBody {
        
        public submit_holiday_requestResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TheWebServiceSoapChannel : Employee_Desktop.ServiceReference1.TheWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TheWebServiceSoapClient : System.ServiceModel.ClientBase<Employee_Desktop.ServiceReference1.TheWebServiceSoap>, Employee_Desktop.ServiceReference1.TheWebServiceSoap {
        
        public TheWebServiceSoapClient() {
        }
        
        public TheWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TheWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TheWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TheWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Employee_Desktop.ServiceReference1.login_employeeResponse Employee_Desktop.ServiceReference1.TheWebServiceSoap.login_employee(Employee_Desktop.ServiceReference1.login_employeeRequest request) {
            return base.Channel.login_employee(request);
        }
        
        public bool login_employee(string email, string password) {
            Employee_Desktop.ServiceReference1.login_employeeRequest inValue = new Employee_Desktop.ServiceReference1.login_employeeRequest();
            inValue.Body = new Employee_Desktop.ServiceReference1.login_employeeRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            Employee_Desktop.ServiceReference1.login_employeeResponse retVal = ((Employee_Desktop.ServiceReference1.TheWebServiceSoap)(this)).login_employee(inValue);
            return retVal.Body.login_employeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Employee_Desktop.ServiceReference1.login_employeeResponse> Employee_Desktop.ServiceReference1.TheWebServiceSoap.login_employeeAsync(Employee_Desktop.ServiceReference1.login_employeeRequest request) {
            return base.Channel.login_employeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Employee_Desktop.ServiceReference1.login_employeeResponse> login_employeeAsync(string email, string password) {
            Employee_Desktop.ServiceReference1.login_employeeRequest inValue = new Employee_Desktop.ServiceReference1.login_employeeRequest();
            inValue.Body = new Employee_Desktop.ServiceReference1.login_employeeRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((Employee_Desktop.ServiceReference1.TheWebServiceSoap)(this)).login_employeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Employee_Desktop.ServiceReference1.submit_holiday_requestResponse Employee_Desktop.ServiceReference1.TheWebServiceSoap.submit_holiday_request(Employee_Desktop.ServiceReference1.submit_holiday_requestRequest request) {
            return base.Channel.submit_holiday_request(request);
        }
        
        public void submit_holiday_request(string email, System.DateTime holiday_start, System.DateTime holiday_end, string holiday_status, bool days_exceeded, bool head_depHead_absent, bool seniorStaff_absent, bool Department_absent) {
            Employee_Desktop.ServiceReference1.submit_holiday_requestRequest inValue = new Employee_Desktop.ServiceReference1.submit_holiday_requestRequest();
            inValue.Body = new Employee_Desktop.ServiceReference1.submit_holiday_requestRequestBody();
            inValue.Body.email = email;
            inValue.Body.holiday_start = holiday_start;
            inValue.Body.holiday_end = holiday_end;
            inValue.Body.holiday_status = holiday_status;
            inValue.Body.days_exceeded = days_exceeded;
            inValue.Body.head_depHead_absent = head_depHead_absent;
            inValue.Body.seniorStaff_absent = seniorStaff_absent;
            inValue.Body.Department_absent = Department_absent;
            Employee_Desktop.ServiceReference1.submit_holiday_requestResponse retVal = ((Employee_Desktop.ServiceReference1.TheWebServiceSoap)(this)).submit_holiday_request(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Employee_Desktop.ServiceReference1.submit_holiday_requestResponse> Employee_Desktop.ServiceReference1.TheWebServiceSoap.submit_holiday_requestAsync(Employee_Desktop.ServiceReference1.submit_holiday_requestRequest request) {
            return base.Channel.submit_holiday_requestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Employee_Desktop.ServiceReference1.submit_holiday_requestResponse> submit_holiday_requestAsync(string email, System.DateTime holiday_start, System.DateTime holiday_end, string holiday_status, bool days_exceeded, bool head_depHead_absent, bool seniorStaff_absent, bool Department_absent) {
            Employee_Desktop.ServiceReference1.submit_holiday_requestRequest inValue = new Employee_Desktop.ServiceReference1.submit_holiday_requestRequest();
            inValue.Body = new Employee_Desktop.ServiceReference1.submit_holiday_requestRequestBody();
            inValue.Body.email = email;
            inValue.Body.holiday_start = holiday_start;
            inValue.Body.holiday_end = holiday_end;
            inValue.Body.holiday_status = holiday_status;
            inValue.Body.days_exceeded = days_exceeded;
            inValue.Body.head_depHead_absent = head_depHead_absent;
            inValue.Body.seniorStaff_absent = seniorStaff_absent;
            inValue.Body.Department_absent = Department_absent;
            return ((Employee_Desktop.ServiceReference1.TheWebServiceSoap)(this)).submit_holiday_requestAsync(inValue);
        }
    }
}
