//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday
    {
        public int Holiday_ID { get; set; }
        public int Employee_ID { get; set; }
        public Nullable<System.DateTime> holiday_start { get; set; }
        public Nullable<System.DateTime> holiday_end { get; set; }
        public string holiday_status { get; set; }
        public Nullable<bool> days_exceeded { get; set; }
        public Nullable<bool> head_depHead_absent { get; set; }
        public Nullable<bool> seniorStaff_absent { get; set; }
        public Nullable<bool> Department_absent { get; set; }
    }
}
